CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE products
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug                  VARCHAR(255)                            NOT NULL,
    name                  VARCHAR(255)                            NOT NULL,
    short_description     VARCHAR(255),
    description           VARCHAR(255),
    type                  SMALLINT                                NOT NULL,
    status                SMALLINT                                NOT NULL,
    featured              BOOLEAN                                 NOT NULL,
    application_available BOOLEAN                                 NOT NULL,
    display_order         INTEGER,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    version               BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE INDEX idx_products_public_listing ON products (status, display_order, name, id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);